GET {{baseUrl}}/api/jobs

###
GET {{baseUrl}}/api/jobs/1

###
POST  {{baseUrl}}/api/jobs
Content-Type: application/json

{
    "title": "Dev Front-End Java/Spring ( Thymeleaf )",
    "description" : "Vaga para Dev Front-End Java",
    "company": "ParaPar Tecnologia",
    "location": "Assuncion-PY",
    "type": "FULL_TIME",
    "level":"MID_LEVEL",
    "salary":"7500.00",
    "skills": [2,3
    ]
}
