GET {{baseUrl}}/api/skills

###
GET {{baseUrl}}/api/skills/3

###
POST {{baseUrl}}/api/skills
Content-Type: application/json

{
    "name": "Dart-Flutter"
}

###
PUT  {{baseUrl}}/api/skills/9
Content-Type: application/json

{
    "name": "Dart-Flutter Kotlin"
}

###
DELETE {{baseUrl}}/api/skills/7
