GET {{baseUrl}}/api/skills

// <!-- GET {{baseUrl}}/api/skills?size=2&page=3 -->

###
GET {{baseUrl}}/api/skills/2

###
POST {{baseUrl}}/api/skills
Content-Type: application/json

{
    "name": "PHP"
}

###
PUT  {{baseUrl}}/api/skills/1100
Content-Type: application/json

{
    "name": "PHP"
}

###
DELETE {{baseUrl}}/api/skills/6
