GET {{baseUrl}}/api/skills

###
GET {{baseUrl}}/api/skills/200

###
POST {{baseUrl}}/api/skills
Content-Type: application/json

{
    "name": "PHP"
}

###
PUT  {{baseUrl}}/api/skills/11
Content-Type: application/json

{
    "name": "PHP"
}

###
DELETE {{baseUrl}}/api/skills/6
